In [9]:
import pandas as pd
import numpy as np

In [10]:
info={
    "Name":["naman","harshit","rahul"],
    "CGPA":[9.5,8.5,7.5]
}
df=pd.DataFrame(info)
print(df)

      Name  CGPA
0    naman   9.5
1  harshit   8.5
2    rahul   7.5

In [11]:
df

      Name  CGPA
0    naman   9.5
1  harshit   8.5
2    rahul   7.5

In [12]:
s=pd.Series([1,2,3,4,5])
print(s, type(s))

# indexing
print(s[1])
print(s[3])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.Series'>
2
4
3

In [13]:
s=pd.Series([24,25,26,27], index=["naman","harshit","rajat","rahul"])
print(s)

print(s["naman"])
print(s["rahul"])

print(s.iloc[0])  # used to access the elements by index if customized labels are used

naman      24
harshit    25
rajat      26
rahul      27
dtype: int64
24
27
24

In [14]:
# properties of the 

# homogeneous means we can store any type of data but it will make all the data as same data type

# Vectorized Operations
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])
print(s1 + s2)

# handle missing values with NaN

# Mutable Values but immutable size
s = pd.Series([1, 2, 3, 4, 5])
s[0] = 100
print(s)

changed_s = s.drop(1)
print(changed_s)
print(s)

0    5
1    7
2    9
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64

In [15]:
# Creating DataFrame in pandas - using dictionary
info = {
"Name" : ["Adam", "Eve", "Bob"],
"Marks" : [78, 99, 85],
"Grade" : ['B', 'O', 'A']
}
df = pd.DataFrame(info)
print(df)
print(type(df))
print(df.index) # row labels
print(df.columns) # column labels

# Creating DataFrom using Numpy array
np_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(np_arr, columns=["Col1", "Col2", "Col3"])
print(df)

# Creating DataFrom using Lists
l = [["Adam", 96], ["Eve", 75], ["Bob", 82], ["Charlie", 92]]
df = pd.DataFrame(l, columns=["Name", "Marks"])
print(df)

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A
<class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Grade'], dtype='str')
   Col1  Col2  Col3
0     1     2     3
1     4     5     6
2     7     8     9
      Name  Marks
0     Adam     96
1      Eve     75
2      Bob     82
3  Charlie     92

In [19]:
df_csv = pd.read_csv("employee_data.csv")# importing data from csv file
print(df_csv)
df_json = pd.read_json("employee_data.json") # importing data from json file
print(df_json)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [22]:
# data frames methods

data = {
'Name': ['Aarav', 'Isha', 'Rohan', 'Sneha', 'Vikram'],
'Age': [25, 30, 35, 40, 45],
'City': ['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Chennai']
}
df = pd.DataFrame(data)
print(df.head())
print(df.tail(3))
print(df.sample())
print(df.info())
print(df.describe())
print(df.nunique())
print(df.dtypes)
print(df.shape)
print(df.columns)

     Name  Age       City
0   Aarav   25      Delhi
1    Isha   30     Mumbai
2   Rohan   35  Bangalore
3   Sneha   40    Kolkata
4  Vikram   45    Chennai
     Name  Age       City
2   Rohan   35  Bangalore
3   Sneha   40    Kolkata
4  Vikram   45    Chennai
    Name  Age   City
0  Aarav   25  Delhi
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   City    5 non-null      str
dtypes: int64(1), str(2)
memory usage: 311.0 bytes
None
             Age
count   5.000000
mean   35.000000
std     7.905694
min    25.000000
25%    30.000000
50%    35.000000
75%    40.000000
max    45.000000
Name    5
Age     5
City    5
dtype: int64
Name      str
Age     int64
City      str
dtype: object
(5, 3)
Index(['Name', 'Age', 'City'], dtype='str')

In [25]:
df=pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [26]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [27]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [34]:
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [37]:
df.loc[2] # this is used for labels
df.loc[0:2]  # in loc in slicing both the value are included

df.iloc[2] # this is used for index
df.iloc[0:2] # in iloc in slicing last value is not included

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [43]:
# cells - rows and columns

df.loc[0:2 ,["city","aqi"]]

df.iloc[0:2, 1:5] # in iloc we only consider numeric values

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006

In [46]:
df.at[0, "city"]
df.iat[0, 2]

cities=df["city"].copy() # this vale make the copy of the data
cities[0]="Mumbai"
print(cities)

0          Mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str