In [1]:
import pandas as pd
import numpy as np

In [2]:
info={
    "Name":["naman","harshit","rahul"],
    "CGPA":[9.5,8.5,7.5]
}
df=pd.DataFrame(info)
print(df)

      Name  CGPA
0    naman   9.5
1  harshit   8.5
2    rahul   7.5

In [3]:
df

      Name  CGPA
0    naman   9.5
1  harshit   8.5
2    rahul   7.5

In [4]:
s=pd.Series([1,2,3,4,5])
print(s, type(s))

# indexing
print(s[1])
print(s[3])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.Series'>
2
4
3

In [5]:
s=pd.Series([24,25,26,27], index=["naman","harshit","rajat","rahul"])
print(s)

print(s["naman"])
print(s["rahul"])

print(s.iloc[0])  # used to access the elements by index if customized labels are used

naman      24
harshit    25
rajat      26
rahul      27
dtype: int64
24
27
24

In [6]:
# properties of the 

# homogeneous means we can store any type of data but it will make all the data as same data type

# Vectorized Operations
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])
print(s1 + s2)

# handle missing values with NaN

# Mutable Values but immutable size
s = pd.Series([1, 2, 3, 4, 5])
s[0] = 100
print(s)

changed_s = s.drop(1)
print(changed_s)
print(s)

0    5
1    7
2    9
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64

In [7]:
# Creating DataFrame in pandas - using dictionary
info = {
"Name" : ["Adam", "Eve", "Bob"],
"Marks" : [78, 99, 85],
"Grade" : ['B', 'O', 'A']
}
df = pd.DataFrame(info)
print(df)
print(type(df))
print(df.index) # row labels
print(df.columns) # column labels

# Creating DataFrom using Numpy array
np_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(np_arr, columns=["Col1", "Col2", "Col3"])
print(df)

# Creating DataFrom using Lists
l = [["Adam", 96], ["Eve", 75], ["Bob", 82], ["Charlie", 92]]
df = pd.DataFrame(l, columns=["Name", "Marks"])
print(df)

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A
<class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Grade'], dtype='str')
   Col1  Col2  Col3
0     1     2     3
1     4     5     6
2     7     8     9
      Name  Marks
0     Adam     96
1      Eve     75
2      Bob     82
3  Charlie     92

In [8]:
df_csv = pd.read_csv("employee_data.csv")# importing data from csv file
print(df_csv)
df_json = pd.read_json("employee_data.json") # importing data from json file
print(df_json)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [9]:
# data frames methods

data = {
'Name': ['Aarav', 'Isha', 'Rohan', 'Sneha', 'Vikram'],
'Age': [25, 30, 35, 40, 45],
'City': ['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Chennai']
}
df = pd.DataFrame(data)
print(df.head())
print(df.tail(3))
print(df.sample())
print(df.info())
print(df.describe())
print(df.nunique())
print(df.dtypes)
print(df.shape)
print(df.columns)

     Name  Age       City
0   Aarav   25      Delhi
1    Isha   30     Mumbai
2   Rohan   35  Bangalore
3   Sneha   40    Kolkata
4  Vikram   45    Chennai
     Name  Age       City
2   Rohan   35  Bangalore
3   Sneha   40    Kolkata
4  Vikram   45    Chennai
    Name  Age   City
0  Aarav   25  Delhi
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   City    5 non-null      str
dtypes: int64(1), str(2)
memory usage: 311.0 bytes
None
             Age
count   5.000000
mean   35.000000
std     7.905694
min    25.000000
25%    30.000000
50%    35.000000
75%    40.000000
max    45.000000
Name    5
Age     5
City    5
dtype: int64
Name      str
Age     int64
City      str
dtype: object
(5, 3)
Index(['Name', 'Age', 'City'], dtype='str')

In [10]:
df=pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [11]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [12]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [13]:
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [14]:
df.loc[2] # this is used for labels
df.loc[0:2]  # in loc in slicing both the value are included

df.iloc[2] # this is used for index
df.iloc[0:2] # in iloc in slicing last value is not included

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [15]:
# cells - rows and columns

df.loc[0:2 ,["city","aqi"]]

df.iloc[0:2, 1:5] # in iloc we only consider numeric values

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006

In [16]:
df.at[0, "city"]
df.iat[0, 2]

cities=df["city"].copy() # this vale make the copy of the data
cities[0]="Mumbai"
print(cities)

0          Mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str

In [17]:
# FILTERING OF DATA
df[df["aqi"] > 100]
df[(df["aqi"] > 100) & (df["temperature"] > 30)]
aqi_data = df[
    (df["aqi"] > 100) & (df["temperature"] > 30)
][["city", "aqi"]]
aqi_data
aqi_data.iloc[0]
aqi_data.loc[6]

city    New York
aqi          155
Name: 6, dtype: object

In [18]:
# QUERY METHOD - it give copy of data
df[(df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]

aqi_val=100
aqi_data = df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]].copy()
aqi_data

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [19]:
# cleaning of the data

df=pd.read_csv("raw_data.csv")
df

# Handle Missing values
df.isnull() # True for null values (NaN)

df.isnull().sum() # counts missing vals per column

df.dropna() # drops rows with missing values

df.dropna(axis = 1) # drops cols with missing values

df.fillna(0) # fills NaN with 0

df["age"] = df["age"].fillna(df["age"].mean()) # fills column with mean

df.ffill() # forward fill

df.bfill() # backward fill

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  51000.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6    Ahmed Khan  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     USA     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [20]:
# handle duplicates values
df.duplicated() # True for duplicate rows
df.duplicated("country") # True for duplicate rows in particular col
df.duplicated(["country", "gender"])

df2=df.copy()
df.drop_duplicates(inplace=True) # drops duplicate rows
df

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [21]:
df=df2

In [22]:
df

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [23]:
# Data Types
df.dtypes

df2 = df.copy()

df2 = df2.fillna(0)

df2["age"] = df2["age"].astype("int64").copy()

df2.dtypes

# date time 
date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtype)

numpy.dtypes.DateTime64DType

In [24]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith   32  Canada   Female  62000.0
3    3          Alex   32     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz   32  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [25]:
df["gender"].str.lower()
# .str.lower() - Convert to lowercase

df["gender"].str.upper()
# .str.upper() - Convert to uppercase

df["gender"].str.capitalize()
# .str.capitalize() - Capitalize strings

df["name"].str.strip()
#.str.strip() - Remove leading/trailing spaces

df["name"].str.split(" ")
# .str.split(" ")- Split into parts based on a separator

df["country"].str.contains("US")
df["country"].str.contains("india" , case=False) # case=False will not take care of the case sensitivity
# .str.contains()  - Check if a value exists in string or not

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: country, dtype: bool

In [26]:
# DATA TRANSFORMATION

df2= df.copy()

df2["tax"] =df2["income"].apply(lambda x : "20%" if x >= 60000 else "10%")

df2

    id          name    age country   gender   income  tax
0    1      John Doe  29.00     USA     Male  55000.0  10%
1    1      John Doe  29.00     USA     Male  55000.0  10%
2    2    Jane Smith  32.75  Canada   Female  62000.0  20%
3    3          Alex  32.75     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.00   Spain   Female      NaN  10%
5    5        Li Wei  27.00   China     Male  51000.0  10%
6    6           NaN  45.00   India   Female  73000.0  20%
7    7    Ahmed Khan  38.00     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.00     USA   Female  62000.0  20%
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.00     USA      NaN  58000.0  10%

In [27]:
gender_map = {"Male" : "M", "Female" : "F", "Unknown" :"U"}
df2["gender"] = df2["gender"].map(gender_map)
df2

    id          name    age country gender   income  tax
0    1      John Doe  29.00     USA      M  55000.0  10%
1    1      John Doe  29.00     USA      M  55000.0  10%
2    2    Jane Smith  32.75  Canada      F  62000.0  20%
3    3          Alex  32.75     USA      U  47000.0  10%
4    4  Maria Garcia  34.00   Spain      F      NaN  10%
5    5        Li Wei  27.00   China      M  51000.0  10%
6    6           NaN  45.00   India      F  73000.0  20%
7    7    Ahmed Khan  38.00     NaN      M  68000.0  20%
8    8    Rachel Lee  29.00     USA      F  62000.0  20%
9    9   Carlos Ruiz  32.75  Mexico      M  45000.0  10%
10  10   Emily Davis  31.00     USA    NaN  58000.0  10%

In [33]:
df2=df2.assign(new_income =df2["income"] *1.1)

In [34]:
df2["country"] = df2["country"].replace("USA", "United States")
df2

    id          name    age        country gender   income  tax  new_income
0    1      John Doe  29.00  United States      M  55000.0  10%     60500.0
1    1      John Doe  29.00  United States      M  55000.0  10%     60500.0
2    2    Jane Smith  32.75         Canada      F  62000.0  20%     68200.0
3    3          Alex  32.75  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.00          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.00          China      M  51000.0  10%     56100.0
6    6           NaN  45.00          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.00            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.00  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz  32.75         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.00  United States    NaN  58000.0  10%     63800.0

In [36]:
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax", "New_Income"]
df2.rename(columns={"Income":"Salary"})

    Id          Name    Age        Country Gender   Salary  Tax  New_Income
0    1      John Doe  29.00  United States      M  55000.0  10%     60500.0
1    1      John Doe  29.00  United States      M  55000.0  10%     60500.0
2    2    Jane Smith  32.75         Canada      F  62000.0  20%     68200.0
3    3          Alex  32.75  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.00          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.00          China      M  51000.0  10%     56100.0
6    6           NaN  45.00          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.00            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.00  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz  32.75         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.00  United States    NaN  58000.0  10%     63800.0

In [39]:
df2.sort_values("Income")
df2 = df2.fillna(50)
# df2.sort_values("Income", ascending=False)   # this is for descending order
df2.sort_values(["Income","Age"])
df2.reset_index() # this is maintain the index but give the new labels to the data

,index,Id,Name,Age,Country,Gender,Income,Tax,New_Income
0,0,1,John Doe,29.00,United States,M,55000.0,10%,60500.0
1,1,1,John Doe,29.00,United States,M,55000.0,10%,60500.0
2,2,2,Jane Smith,32.75,Canada,F,62000.0,20%,68200.0
3,3,3,Alex,32.75,United States,U,47000.0,10%,51700.0
4,4,4,Maria Garcia,34.00,Spain,F,50.0,10%,50.0
5,5,5,Li Wei,27.00,China,M,51000.0,10%,56100.0
6,6,6,50,45.00,India,F,73000.0,20%,80300.0
7,7,7,Ahmed Khan,38.00,50,M,68000.0,20%,74800.0
8,8,8,Rachel Lee,29.00,United States,F,62000.0,20%,68200.0
9,9,9,Carlos Ruiz,32.75,Mexico,M,45000.0,10%,49500.0
10,10,10,Emily Davis,31.00,United States,50,58000.0,10%,63800.0

In [38]:
df2.sort_index()

    Id          Name    Age        Country Gender   Income  Tax  New_Income
0    1      John Doe  29.00  United States      M  55000.0  10%     60500.0
1    1      John Doe  29.00  United States      M  55000.0  10%     60500.0
2    2    Jane Smith  32.75         Canada      F  62000.0  20%     68200.0
3    3          Alex  32.75  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.00          Spain      F     50.0  10%        50.0
5    5        Li Wei  27.00          China      M  51000.0  10%     56100.0
6    6            50  45.00          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.00             50      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.00  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz  32.75         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.00  United States     50  58000.0  10%     63800.0

In [41]:
# Ranking
df2["ranking"]=df2["Income"].rank(ascending=False)
df2
# reorder columns

,Id,Name,Age,Country,Gender,Income,Tax,New_Income,ranking
0,1,John Doe,29.00,United States,M,55000.0,10%,60500.0,6.5
1,1,John Doe,29.00,United States,M,55000.0,10%,60500.0,6.5
2,2,Jane Smith,32.75,Canada,F,62000.0,20%,68200.0,3.5
3,3,Alex,32.75,United States,U,47000.0,10%,51700.0,9.0
4,4,Maria Garcia,34.00,Spain,F,50.0,10%,50.0,11.0
5,5,Li Wei,27.00,China,M,51000.0,10%,56100.0,8.0
6,6,50,45.00,India,F,73000.0,20%,80300.0,1.0
7,7,Ahmed Khan,38.00,50,M,68000.0,20%,74800.0,2.0
8,8,Rachel Lee,29.00,United States,F,62000.0,20%,68200.0,3.5
9,9,Carlos Ruiz,32.75,Mexico,M,45000.0,10%,49500.0,10.0
10,10,Emily Davis,31.00,United States,50,58000.0,10%,63800.0,5.0